export default {
  "block-closing-brace-space-after": require("./block-closing-brace-space-after"),
  "block-closing-brace-space-before": require("./block-closing-brace-space-before"),
  "block-closing-brace-newline-after": require("./block-closing-brace-newline-after"),
  "block-closing-brace-newline-before": require("./block-closing-brace-newline-before"),
  "block-opening-brace-space-after": require("./block-opening-brace-space-after"),
  "block-opening-brace-space-before": require("./block-opening-brace-space-before"),
  "block-opening-brace-newline-after": require("./block-opening-brace-newline-after"),
  "block-opening-brace-newline-before": require("./block-opening-brace-newline-before"),
  "declaration-bang-space-after": require("declaration-bang-space-after"),
  "declaration-bang-space-before": require("declaration-bang-space-before"),
  "declaration-block-trailing-semicolon": require("./declaration-block-trailing-semicolon"),
  "declaration-colon-space-after": require("./declaration-colon-space-after"),
  "declaration-colon-space-before": require("./declaration-colon-space-before"),
  "declaration-comma-space-after": require("./declaration-comma-space-after"),
  "declaration-comma-space-before": require("./declaration-comma-space-before"),
  "declaration-no-important": require("./declaration-no-important"),
  "function-comma-space-after": require("./function-comma-space-after"),
  "function-comma-space-before": require("./function-comma-space-before"),
  "number-leading-zero": require("./number-leading-zero"),
  "rule-set-no-single-line": require("./rule-set-no-single-line"),
  "selector-combinator-space-after": require("./selector-combinator-space-after"),
  "selector-combinator-space-before": require("./selector-combinator-space-before"),
}
