// NOTICE: This file is generated by Rollup. To modify it,
// please instead edit the ESM counterpart and rebuild with Rollup (npm run build).
'use strict';

const mediaQueryListParser = require('@csstools/media-query-list-parser');
const atRuleParamIndex = require('../../utils/atRuleParamIndex.cjs');
const isCustomMediaQuery = require('../../utils/isCustomMediaQuery.cjs');
const parseCustomMediaQuery = require('../../utils/parseCustomMediaQuery.cjs');
const parseMediaQuery = require('../../utils/parseMediaQuery.cjs');
const report = require('../../utils/report.cjs');
const ruleMessages = require('../../utils/ruleMessages.cjs');
const validateOptions = require('../../utils/validateOptions.cjs');

const ruleName = 'no-unknown-custom-media';

const messages = ruleMessages(ruleName, {
	expected: (mediaName) => `Unexpected unknown custom media "${mediaName}"`,
});

const meta = {
	url: 'https://stylelint.io/user-guide/rules/no-unknown-custom-media',
};

/** @type {import('stylelint').Rule} */
const rule = (primary) => {
	return (root, result) => {
		const validOptions = validateOptions(result, ruleName, { actual: primary });

		if (!validOptions) return;

		const declaredCustomMediaQueries = new Set();

		root.walkAtRules((atRule) => {
			const atRuleName = atRule.name.toLowerCase();

			if (atRuleName !== 'custom-media' && atRuleName !== 'media') {
				return;
			}

			if (atRuleName === 'custom-media') {
				const customMediaQuery = parseCustomMediaQuery(atRule);
				const customMediaQueryName = customMediaQuery && customMediaQuery.getName();

				if (!customMediaQueryName) return;

				declaredCustomMediaQueries.add(customMediaQueryName);

				return;
			}

			let usedCustomMediaQueryName = '';

			const mediaQueryList = parseMediaQuery(atRule);

			mediaQueryList.forEach((mediaQuery) => {
				if (mediaQueryListParser.isMediaQueryInvalid(mediaQuery)) return;

				mediaQuery.walk(({ node }) => {
					if (mediaQueryListParser.isMediaFeature(node) && isCustomMediaQuery(node.getName())) {
						usedCustomMediaQueryName = node.getName();
					}
				});
			});

			if (declaredCustomMediaQueries.has(usedCustomMediaQueryName)) {
				return;
			}

			const index = atRuleParamIndex(atRule);
			const endIndex = index + usedCustomMediaQueryName.length + 1;

			report({
				message: messages.expected,
				messageArgs: [usedCustomMediaQueryName, primary],
				node: atRule,
				index,
				endIndex,
				result,
				ruleName,
			});
		});
	};
};

rule.ruleName = ruleName;
rule.messages = messages;
rule.meta = meta;

module.exports = rule;
