module.exports = {
	rules: {
		'alpha-value-notation': 'number',
		'annotation-no-unknown': true,
		'at-rule-allowed-list': ['keyframes'],
		'at-rule-disallowed-list': ['keyframes'],
		'at-rule-empty-line-before': 'always',
		'at-rule-no-unknown': true,
		'at-rule-no-vendor-prefix': true,
		'at-rule-property-required-list': { 'font-face': ['font-display'] },
		'block-no-empty': true,
		'color-function-notation': 'modern',
		'color-hex-alpha': 'always',
		'color-hex-length': 'short',
		'color-named': 'always-where-possible',
		'color-no-hex': true,
		'color-no-invalid-hex': true,
		'comment-empty-line-before': 'always',
		'comment-no-empty': true,
		'comment-pattern': /regex/,
		'comment-whitespace-inside': 'always',
		'comment-word-disallowed-list': /regex/,
		'custom-media-pattern': /regex/,
		'custom-property-empty-line-before': 'always',
		'custom-property-no-missing-var-function': true,
		'custom-property-pattern': /regex/,
		'declaration-block-no-duplicate-custom-properties': true,
		'declaration-block-no-duplicate-properties': true,
		'declaration-block-no-redundant-longhand-properties': true,
		'declaration-block-no-shorthand-property-overrides': true,
		'declaration-block-single-line-max-declarations': 1,
		'declaration-empty-line-before': 'always',
		'declaration-no-important': true,
		'declaration-property-max-values': { border: 1 },
		'declaration-property-unit-allowed-list': { 'font-size': ['px'] },
		'declaration-property-unit-disallowed-list': { 'font-size': ['px'] },
		'declaration-property-value-allowed-list': { transform: ['scale'] },
		'declaration-property-value-disallowed-list': { transform: ['scale'] },
		'declaration-property-value-no-unknown': true,
		'font-family-name-quotes': 'always-where-required',
		'font-family-no-duplicate-names': true,
		'font-family-no-missing-generic-family-keyword': true,
		'font-weight-notation': 'numeric',
		'function-allowed-list': ['calc'],
		'function-calc-no-unspaced-operator': true,
		'function-disallowed-list': ['calc'],
		'function-linear-gradient-no-nonstandard-direction': true,
		'function-name-case': 'lower',
		'function-no-unknown': true,
		'function-url-no-scheme-relative': true,
		'function-url-quotes': 'always',
		'function-url-scheme-allowed-list': ['https'],
		'function-url-scheme-disallowed-list': ['https'],
		'hue-degree-notation': 'angle',
		'import-notation': 'string',
		'keyframe-block-no-duplicate-selectors': true,
		'keyframe-declaration-no-important': true,
		'keyframe-selector-notation': 'keyword',
		'keyframes-name-pattern': /regex/,
		'length-zero-no-unit': true,
		'max-nesting-depth': 1,
		'media-feature-name-allowed-list': ['max-width'],
		'media-feature-name-disallowed-list': ['max-width'],
		'media-feature-name-no-unknown': true,
		'media-feature-name-no-vendor-prefix': true,
		'media-feature-name-unit-allowed-list': { width: ['em'] },
		'media-feature-name-value-allowed-list': { 'max-width': ['1024px'] },
		'media-feature-name-value-no-unknown': true,
		'media-feature-range-notation': 'context',
		'media-query-no-invalid': true,
		'named-grid-areas-no-invalid': true,
		'no-descending-specificity': true,
		'no-duplicate-at-import-rules': true,
		'no-duplicate-selectors': true,
		'no-empty-source': true,
		'no-invalid-double-slash-comments': true,
		'no-invalid-position-at-import-rule': true,
		'no-irregular-whitespace': true,
		'no-unknown-animations': true,
		'no-unknown-custom-properties': true,
		'number-max-precision': 1,
		'property-allowed-list': ['display'],
		'property-disallowed-list': ['display'],
		'property-no-unknown': true,
		'property-no-vendor-prefix': true,
		'rule-empty-line-before': 'always',
		'rule-selector-property-disallowed-list': { a: ['color'] },
		'selector-anb-no-unmatchable': true,
		'selector-attribute-name-disallowed-list': ['class'],
		'selector-attribute-operator-allowed-list': ['*='],
		'selector-attribute-operator-disallowed-list': ['*='],
		'selector-attribute-quotes': 'always',
		'selector-class-pattern': /regex/,
		'selector-combinator-allowed-list': ['>'],
		'selector-combinator-disallowed-list': ['>'],
		'selector-disallowed-list': ['a > *'],
		'selector-id-pattern': /regex/,
		'selector-max-attribute': 1,
		'selector-max-class': 1,
		'selector-max-combinators': 1,
		'selector-max-compound-selectors': 1,
		'selector-max-id': 1,
		'selector-max-pseudo-class': 1,
		'selector-max-specificity': '0,2,0',
		'selector-max-type': 1,
		'selector-max-universal': 1,
		'selector-nested-pattern': /regex/,
		'selector-no-qualifying-type': true,
		'selector-no-vendor-prefix': true,
		'selector-not-notation': 'simple',
		'selector-pseudo-class-allowed-list': ['hover'],
		'selector-pseudo-class-disallowed-list': ['hover'],
		'selector-pseudo-class-no-unknown': true,
		'selector-pseudo-element-allowed-list': ['before'],
		'selector-pseudo-element-colon-notation': 'single',
		'selector-pseudo-element-disallowed-list': ['before'],
		'selector-pseudo-element-no-unknown': true,
		'selector-type-case': 'lower',
		'selector-type-no-unknown': true,
		'shorthand-property-no-redundant-values': true,
		'string-no-newline': true,
		'time-min-milliseconds': 1,
		'unit-allowed-list': ['px'],
		'unit-disallowed-list': ['px'],
		'unit-no-unknown': true,
		'value-keyword-case': 'lower',
		'value-no-vendor-prefix': true,
	},
};
