import test from "tape"
import isKnownUnit from "../isKnownUnit"

test("isKnownUnit", t => {
  t.notOk(isKnownUnit("pix"))
  t.notOk(isKnownUnit("pixels"))
  t.ok(isKnownUnit("em"))
  t.ok(isKnownUnit("ex"))
  t.ok(isKnownUnit("ch"))
  t.ok(isKnownUnit("rem"))
  t.ok(isKnownUnit("%"))
  t.ok(isKnownUnit("vh"))
  t.ok(isKnownUnit("vw"))
  t.ok(isKnownUnit("vmin"))
  t.ok(isKnownUnit("vmax"))
  t.ok(isKnownUnit("vm"))
  t.ok(isKnownUnit("px"))
  t.ok(isKnownUnit("mm"))
  t.ok(isKnownUnit("cm"))
  t.ok(isKnownUnit("in"))
  t.ok(isKnownUnit("pt"))
  t.ok(isKnownUnit("pc"))
  t.ok(isKnownUnit("s"))
  t.ok(isKnownUnit("ms"))
  t.ok(isKnownUnit("deg"))
  t.ok(isKnownUnit("grad"))
  t.ok(isKnownUnit("turn"))
  t.ok(isKnownUnit("rad"))
  t.ok(isKnownUnit("Hz"))
  t.ok(isKnownUnit("kHz"))
  t.ok(isKnownUnit("dpi"))
  t.ok(isKnownUnit("dpcm"))
  t.ok(isKnownUnit("dppx"))
  t.end()
})
