import test from "tape"
import isKnownPseudoElement from "../isKnownPseudoElement"

test("isKnownUnit", t => {
  t.notOk(isKnownPseudoElement("pseudo"))
  t.notOk(isKnownPseudoElement("pSeUdO"))
  t.notOk(isKnownPseudoElement("PSEUDO"))
  t.notOk(isKnownPseudoElement("element"))
  t.ok(isKnownPseudoElement("before"))
  t.ok(isKnownPseudoElement("bEfOrE"))
  t.ok(isKnownPseudoElement("BEFORE"))
  t.ok(isKnownPseudoElement("after"))
  t.ok(isKnownPseudoElement("first-line"))
  t.ok(isKnownPseudoElement("first-letter"))
  t.ok(isKnownPseudoElement("before"))
  t.ok(isKnownPseudoElement("after"))
  t.ok(isKnownPseudoElement("first-line"))
  t.ok(isKnownPseudoElement("first-letter"))
  t.ok(isKnownPseudoElement("selection"))
  t.ok(isKnownPseudoElement("spelling-error"))
  t.ok(isKnownPseudoElement("grammar-error"))
  t.ok(isKnownPseudoElement("backdrop"))
  t.ok(isKnownPseudoElement("marker"))
  t.ok(isKnownPseudoElement("placeholder"))
  t.ok(isKnownPseudoElement("shadow"))
  t.ok(isKnownPseudoElement("content"))

  t.ok(isKnownPseudoElement("first-line", { only: "oneColonNotation" }))
  t.ok(isKnownPseudoElement("first-letter", { only: "oneColonNotation" }))
  t.ok(isKnownPseudoElement("before", { only: "oneColonNotation" }))
  t.ok(isKnownPseudoElement("after", { only: "oneColonNotation" }))
  t.notOk(isKnownPseudoElement("selection", { only: "oneColonNotation" }))
  t.end()
})
