declare module '@stylelint/postcss-css-in-js';
declare module '@stylelint/postcss-markdown';
declare module 'import-lazy';
declare module 'postcss-html';
declare module 'postcss-less';
declare module 'postcss-sass';
declare module 'postcss-scss';
declare module 'sugarss';
declare module 'table';
