import rule from '../index.mjs';
const { messages, ruleName } = rule;

testRule({
	ruleName,
	config: true,

	accept: [
		{
			code: '@charset "utf-8";',
		},
		{
			code: '@charset "utf-8";\na { color: red; }',
		},
		{
			code: '@charset "UTF-8";',
			description: 'encoding labels are case-insensitive',
		},
		{
			code: '@charset "windows-1252";',
		},
		{
			code: 'a { color: red; }',
			description: 'no rule at all',
		},
		{
			code: '\uFEFFa { color: red; }',
			description: 'byte order mark without the rule',
		},
		{
			code: "/* @charset 'utf-8'; */\na { color: red; }",
			description: 'within a comment',
		},
		{
			code: 'a { content: "@charset \'utf-8\';"; }',
			description: 'within a string',
		},
	],

	reject: [
		{
			code: "@charset 'utf-8';",
			message: messages.rejected('expected double quotes around the encoding label'),
			line: 1,
			column: 1,
			endLine: 1,
			endColumn: 18,
			description: 'single quotes around the encoding label',
		},
		{
			code: '@charset utf-8;',
			message: messages.rejected('expected double quotes around the encoding label'),
			line: 1,
			column: 1,
			endLine: 1,
			endColumn: 16,
			description: 'unquoted encoding label',
		},
		{
			code: '@CHARSET "utf-8";',
			message: messages.rejected('expected "@charset" to be lowercase'),
			line: 1,
			column: 1,
			endLine: 1,
			endColumn: 18,
			description: 'uppercase name',
		},
		{
			code: '@charset  "utf-8";',
			message: messages.rejected('expected a single space after "@charset"'),
			line: 1,
			column: 1,
			endLine: 1,
			endColumn: 19,
			description: 'two spaces after the name',
		},
		{
			code: '@charset"utf-8";',
			message: messages.rejected('expected a single space after "@charset"'),
			line: 1,
			column: 1,
			endLine: 1,
			endColumn: 17,
			description: 'no space after the name',
		},
		{
			code: '@charset\t"utf-8";',
			message: messages.rejected('expected a single space after "@charset"'),
			line: 1,
			column: 1,
			endLine: 1,
			endColumn: 18,
			description: 'tab after the name',
		},
		{
			code: '@charset\n"utf-8";',
			message: messages.rejected('expected a single space after "@charset"'),
			line: 1,
			column: 1,
			endLine: 2,
			endColumn: 9,
			description: 'newline after the name',
		},
		{
			code: '@charset /* qux */ "utf-8";',
			message: messages.rejected('expected a single space after "@charset"'),
			line: 1,
			column: 1,
			endLine: 1,
			endColumn: 28,
			description: 'comment after the name',
		},
		{
			code: '@charset "utf-8" ;',
			message: messages.rejected('expected a semicolon directly after the closing quote'),
			line: 1,
			column: 1,
			endLine: 1,
			endColumn: 19,
			description: 'space before the semicolon',
		},
		{
			code: '@charset "utf-8"',
			message: messages.rejected('expected a semicolon directly after the closing quote'),
			line: 1,
			column: 1,
			endLine: 1,
			endColumn: 17,
			description: 'missing semicolon',
		},
		{
			code: '@charset "utf-8" {}\na { color: red; }',
			message: messages.rejected('expected a semicolon directly after the closing quote'),
			line: 1,
			column: 1,
			endLine: 1,
			endColumn: 20,
			description: 'block instead of a semicolon',
		},
		{
			code: '@charset "utf-8"{}\na { color: red; }',
			message: messages.rejected('expected a semicolon directly after the closing quote'),
			line: 1,
			column: 1,
			endLine: 1,
			endColumn: 19,
			description: 'block instead of a semicolon, without a space',
		},
		{
			code: '@charset "utf-8"\n@import "foo.css";',
			message: messages.rejected('expected a semicolon directly after the closing quote'),
			line: 1,
			column: 1,
			endLine: 2,
			endColumn: 19,
			description: 'missing semicolon before another at-rule',
		},
		{
			code: '@charset "utf-8" foo;',
			message: messages.rejected('expected a semicolon directly after the closing quote'),
			line: 1,
			column: 1,
			endLine: 1,
			endColumn: 22,
			description: 'extra content after the encoding label',
		},
		{
			code: '\n@charset "utf-8";',
			message: messages.rejected('expected it to be at the very start of the stylesheet'),
			line: 2,
			column: 1,
			endLine: 2,
			endColumn: 18,
			description: 'newline before the rule',
		},
		{
			code: '/* foo */\n@charset "utf-8";',
			message: messages.rejected('expected it to be at the very start of the stylesheet'),
			line: 2,
			column: 1,
			endLine: 2,
			endColumn: 18,
			description: 'comment before the rule',
		},
		{
			code: 'a { color: red; }\n@charset "utf-8";',
			message: messages.rejected('expected it to be at the very start of the stylesheet'),
			line: 2,
			column: 1,
			endLine: 2,
			endColumn: 18,
			description: 'style rule before the rule',
		},
		{
			code: '@media all {\n  @charset "utf-8";\n}',
			message: messages.rejected('expected it to be at the very start of the stylesheet'),
			line: 2,
			column: 3,
			endLine: 2,
			endColumn: 20,
			description: 'within a block',
		},
		{
			code: '@charset "utf-8";\n@charset "utf-8";',
			message: messages.rejected('expected it to be at the very start of the stylesheet'),
			line: 2,
			column: 1,
			endLine: 2,
			endColumn: 18,
			description: 'second rule',
		},
		{
			code: '@CHARSET  "utf-8";',
			description: 'uppercase name and two spaces',
			warnings: [
				{
					message: messages.rejected('expected "@charset" to be lowercase'),
					line: 1,
					column: 1,
					endLine: 1,
					endColumn: 19,
				},
				{
					message: messages.rejected('expected a single space after "@charset"'),
					line: 1,
					column: 1,
					endLine: 1,
					endColumn: 19,
				},
			],
		},
		{
			code: '\uFEFF@charset "utf-8";',
			message: messages.rejected('expected no byte order mark before "@charset"'),
			line: 1,
			column: 1,
			endLine: 1,
			endColumn: 18,
			description: 'byte order mark before a valid rule',
		},
		{
			code: "\uFEFF@charset 'utf-8';",
			message: messages.rejected('expected no byte order mark before "@charset"'),
			line: 1,
			column: 1,
			endLine: 1,
			endColumn: 18,
			description: 'byte order mark before an invalid rule',
		},
	],
});
