name: '🐛 Report a bug'
description: 'Is something not working as you expect?'
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug!

        Please [search our issues](https://github.com/search?q=repo%3Astylelint%2Fstylelint+&type=issues) to check that the bug hasn't already been reported.

        You can help us fix the bug more quickly by:
        1. Figuring out what needs doing and proposing a fix.
        2. After the bug is confirmed, [contributing](https://github.com/stylelint/stylelint/blob/main/CONTRIBUTING.md) a pull request.
  - type: textarea
    id: reproduce-bug
    attributes:
      label: 'What minimal example or steps are needed to reproduce the bug?'
      description: 'Provide the smallest possible reproducible example or steps.'
      placeholder: |
        ```css
        a {
          colo: red;
        }
        ```

        Or

        1. Step 1
        2. Step 2
        3. ...
    validations:
      required: true
  - type: textarea
    id: stylelint-configuration
    attributes:
      label: 'What minimal configuration is needed to reproduce the bug?'
      description: 'Provide the smallest possible reproducible configuration.'
      placeholder: |
        ```json
        {
          "rules": {
            "declaration-block-no-duplicate-properties": true
          }
        }
        ```
    validations:
      required: true
  - type: textarea
    id: stylelint-run
    attributes:
      label: 'How did you run Stylelint?'
      description: 'If applicable, provide a [Stylelint demo](https://stylelint.io/demo/).'
      placeholder: |
        [Demo](https://stylelint.io/demo/#...)

        Or

        ```shell
        stylelint "**/*.css" --config myconfig.json
        ```
    validations:
      required: true
  - type: textarea
    id: stylelint-version
    attributes:
      label: 'Which Stylelint-related dependencies are you using?'
      description: 'Provide versions from your `package.json`.'
      placeholder: |
        ```json
        {
          "stylelint": "15.6.0",
          "stylelint-config-standard": "33.0.0"
        }
        ```
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: 'What did you expect to happen?'
      placeholder: |
        No problems to be reported.
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: 'What actually happened?'
      placeholder: |
        The following problems were reported:

        ```
        test.css
         4:9   ✖  Unexpected unknown property "colo" (property-no-unknown)
        ```
    validations:
      required: true
  - type: textarea
    id: proposal-bugfix
    attributes:
      label: 'Do you have a proposal to fix the bug?'
      description: 'Help us by proposing your ideas.'
    validations:
      required: false
