name: '🐛 Report a bug'
description: 'Is something not working as you expect?'
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug!

        Please [search our issues](https://github.com/search?q=repo%3Astylelint%2Fstylelint&type=issues) to check that the bug hasn't already been reported.

        You can help us fix the bug more quickly by:
        1. Figuring out what needs doing and proposing it in the issue.
        2. After the bug is confirmed, [contributing](https://github.com/stylelint/stylelint/blob/main/CONTRIBUTING.md) a pull request.
  - type: textarea
    id: reproduce-bug
    attributes:
      label: 'What steps are needed to reproduce the bug?'
      description: 'Provide the smallest reproducible CSS example or steps.'
      placeholder: |
        ```css
        a {
          colo: red;
        }
        ```

        Or

        1. Step 1
        2. Step 2
        3. ...
    validations:
      required: true
  - type: textarea
    id: stylelint-configuration
    attributes:
      label: 'What Stylelint configuration is needed to reproduce the bug?'
      description: 'Provide the smallest reproducible example.'
      placeholder: |
        ```json
        {
          "rules": {
            "declaration-block-no-duplicate-properties": true
          }
        }
        ```
    validations:
      required: true
  - type: textarea
    id: stylelint-run
    attributes:
      label: 'How did you run Stylelint?'
      description: 'For example, CLI, Node.js API, PostCSS plugin, or [Stylelint demo](https://stylelint.io/demo/).'
      placeholder: |
        ```shell
        stylelint "**/*.css" --config myconfig.json
        ```

        Or

        https://stylelint.io/demo/#...
    validations:
      required: true
  - type: textarea
    id: stylelint-version
    attributes:
      label: 'Which version of Stylelint or dependencies are you using?'
      placeholder: |
        15.6.0

        Or

        ```json
        {
          "stylelint": "15.6.0",
          "stylelint-config-standard": "33.0.0"
        }
        ```
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: 'What did you expect to happen?'
      placeholder: |
        No problems to be reported.
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: 'What actually happened?'
      description: 'For example, what warnings or errors did you get?'
      placeholder: |
        The following problems were reported:

        ```
        test.css
         4:9   ✖  Unexpected unknown property "colo" (property-no-unknown)
        ```
    validations:
      required: true
  - type: textarea
    id: non-standard-syntax
    attributes:
      label: 'Does the bug relate to non-standard syntax?'
      description: 'For example, a construct from SCSS, Less or CSS-in-JS.'
      placeholder: |
        Yes, it's related to SCSS nested properties.
    validations:
      required: false
  - type: textarea
    id: proposal-bugfix
    attributes:
      label: 'Proposal to fix the bug'
      description: 'If you know what needs doing, please propose it below.'
    validations:
      required: false
