name: '🚀 Request a feature'
description: 'Do you want to suggest a new feature?'
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to request a feature!
  - type: textarea
    id: what-problem
    attributes:
      label: "What is the problem you're trying to solve?"
    validations:
      required: true
  - type: textarea
    id: what-solution
    attributes:
      label: 'What solution would you like to see?'
    validations:
      required: true
