// NOTICE: This file is generated by Rollup. To modify it,
// please instead edit the ESM counterpart and rebuild with Rollup (npm run build).
'use strict';

/**
 * @typedef {import('stylelint').Severity} Severity
 *
 * @param {Severity} severity
 * @param {boolean} maybeFixable
 * @param {Record<Severity, number>} counts
 * @returns {void}
 */
function calcMaybeFixableCounts(severity, maybeFixable, counts) {
	if (maybeFixable !== true) return;

	if (severity !== 'error' && severity !== 'warning') return;

	counts[severity] += 1;
}

module.exports = calcMaybeFixableCounts;
