'use strict';

const DEFAULT_CACHE_LOCATION = './.stylelintcache';
const CACHE_STRATEGY_METADATA = 'metadata';
const CACHE_STRATEGY_CONTENT = 'content';
const DEFAULT_CACHE_STRATEGY = CACHE_STRATEGY_METADATA;

const DEFAULT_IGNORE_FILENAME = '.stylelintignore';

const DEFAULT_FORMATTER = 'string';

// NOTE: Partially based on `sysexits.h`.
const EXIT_CODE_SUCCESS = 0;
const EXIT_CODE_FATAL = 1;
const EXIT_CODE_VIOLATION = 2;
const EXIT_CODE_USAGE = 64;
const EXIT_CODE_CONFIG = 78;

exports.CACHE_STRATEGY_CONTENT = CACHE_STRATEGY_CONTENT;
exports.CACHE_STRATEGY_METADATA = CACHE_STRATEGY_METADATA;
exports.DEFAULT_CACHE_LOCATION = DEFAULT_CACHE_LOCATION;
exports.DEFAULT_CACHE_STRATEGY = DEFAULT_CACHE_STRATEGY;
exports.DEFAULT_FORMATTER = DEFAULT_FORMATTER;
exports.DEFAULT_IGNORE_FILENAME = DEFAULT_IGNORE_FILENAME;
exports.EXIT_CODE_CONFIG = EXIT_CODE_CONFIG;
exports.EXIT_CODE_FATAL = EXIT_CODE_FATAL;
exports.EXIT_CODE_SUCCESS = EXIT_CODE_SUCCESS;
exports.EXIT_CODE_USAGE = EXIT_CODE_USAGE;
exports.EXIT_CODE_VIOLATION = EXIT_CODE_VIOLATION;
