'use strict';

const DEFAULT_CACHE_LOCATION = './.stylelintcache';
const CACHE_STRATEGY_METADATA = 'metadata';
const CACHE_STRATEGY_CONTENT = 'content';
const DEFAULT_CACHE_STRATEGY = CACHE_STRATEGY_METADATA;

const DEFAULT_IGNORE_FILENAME = '.stylelintignore';

const DEFAULT_FORMATTER = 'string';

const EXIT_CODE_ERROR = 2;

module.exports = {
	DEFAULT_CACHE_LOCATION,
	CACHE_STRATEGY_METADATA,
	CACHE_STRATEGY_CONTENT,
	DEFAULT_CACHE_STRATEGY,

	DEFAULT_IGNORE_FILENAME,

	DEFAULT_FORMATTER,

	EXIT_CODE_ERROR,
};
