// NOTICE: This file is generated by Rollup. To modify it,
// please instead edit the ESM counterpart and rebuild with Rollup (npm run build).
'use strict';

const createPartialStylelintResult = require('./createPartialStylelintResult.cjs');
const getConfigForFile = require('./getConfigForFile.cjs');

/**
 * @param {import('stylelint').InternalApi} stylelint
 * @param {import('stylelint').PostcssResult} [postcssResult]
 * @param {string} [filePath]
 * @param {import('stylelint').CssSyntaxError} [cssSyntaxError]
 * @return {Promise<import('stylelint').LintResult>}
 */
async function createStylelintResult(
	stylelint,
	postcssResult,
	filePath,
	cssSyntaxError,
) {
	let stylelintResult = createPartialStylelintResult(postcssResult, cssSyntaxError);

	const configForFile = await getConfigForFile(stylelint, filePath, filePath);

	const config = configForFile === null ? {} : configForFile.config;

	config.processors?.forEach(
		(
			/** @type {import('stylelint').Processor} */
			processor,
		) => {
			processor.postprocess?.(stylelintResult);
		},
	);

	return stylelintResult;
}

module.exports = createStylelintResult;
