// NOTICE: This file is generated by Rollup. If you want to change,
// please edit its ESM version file instead of this one.
'use strict';

/**
 * @type {import('stylelint')['createPlugin']}
 */
function createPlugin(ruleName, rule) {
	return {
		ruleName,
		rule,
	};
}

module.exports = createPlugin;
