// NOTICE: This file is generated by Rollup. To modify it,
// please instead edit the ESM counterpart and rebuild with Rollup (npm run build).
'use strict';

/**
 * @param {import('stylelint').PostcssResult} result
 * @param {string} name
 * @param {import('stylelint').FixerData} data
 */
const addFixer = (result, name, data) => {
	const list = result.stylelint.fixersData[name];

	if (!list) result.stylelint.fixersData[name] = [data];
	else list.push(data);
};

module.exports = addFixer;
