// NOTICE: This file is generated by Rollup. To modify it,
// please instead edit the ESM counterpart and rebuild with Rollup (npm run build).
'use strict';

/**
 * @param {import('postcss').AtRule} atRule
 * @returns {number}
 */
function atRuleRawsAfterIndex(atRule) {
	return atRule.source?.end?.offset ?? atRule.toString().length;
}

module.exports = atRuleRawsAfterIndex;
