// NOTICE: This file is generated by Rollup. To modify it,
// please instead edit the ESM counterpart and rebuild with Rollup (npm run build).
'use strict';

const atRuleParamIndex = require('./atRuleParamIndex.cjs');

/**
 * @param {import('postcss').AtRule} atRule
 * @returns {number}
 */
function atRuleRawsBetweenIndex(atRule) {
	return atRuleParamIndex(atRule) + atRule.params.length;
}

module.exports = atRuleRawsBetweenIndex;
