// NOTICE: This file is generated by Rollup. If you want to change,
// please edit its ESM version file instead of this one.
'use strict';

/**
 * @param {string} source
 * @param {string} [blurChar]
 * @returns {string}
 */
function blurInterpolation(source, blurChar = ' ') {
	return source.replace(/[#@{}]+/g, blurChar);
}

module.exports = blurInterpolation;
