// NOTICE: This file is generated by Rollup. To modify it,
// please instead edit the ESM counterpart and rebuild with Rollup (npm run build).
'use strict';

const valueParser = require('postcss-value-parser');

/**
 * @param {string} value
 */
function dimensionUnitIsEmpty(value) {
	const dimension = valueParser.unit(value);

	return dimension && dimension.unit === '';
}

module.exports = dimensionUnitIsEmpty;
