// NOTICE: This file is generated by Rollup. To modify it,
// please instead edit the ESM counterpart and rebuild with Rollup (npm run build).
'use strict';

const process = require('node:process');

// Each code must be unique across all warning types (ExperimentalWarning, DeprecationWarning, etc.).
// To avoid conflicts, we start experimental warning codes from 1001.
const CODES = {
	SUPPRESSIONS: '1001',
};

const emittedWarnings = new Set();

/**
 * Use this function for experimental warnings, instead of `process.emitWarning()`.
 *
 * @param {string} message
 * @param {keyof CODES} codeKey
 * @param {string} detail
 * @returns {void}
 */
function emitExperimentalWarning(message, codeKey, detail) {
	const code = CODES[codeKey];

	const key = JSON.stringify({
		message,
		options: { type: 'ExperimentalWarning', code: `stylelint:${code}`, detail },
	});

	if (emittedWarnings.has(key)) return;

	emittedWarnings.add(key);

	process.emitWarning(message, { type: 'ExperimentalWarning', code: `stylelint:${code}`, detail });
}

/**
 * Clear the already emitted experimental warnings.
 * Only useful in tests.
 *
 * @private
 */
function clearEmittedExperimentalWarnings() {
	emittedWarnings.clear();
}

exports.clearEmittedExperimentalWarnings = clearEmittedExperimentalWarnings;
exports.default = emitExperimentalWarning;
