// NOTICE: This file is generated by Rollup. To modify it,
// please instead edit the ESM counterpart and rebuild with Rollup (npm run build).
'use strict';

const validateTypes = require('./validateTypes.cjs');

/** @typedef {import('stylelint').Range} Range */
/** @typedef {import('postcss').Node} Node */
/** @typedef {(node: Node, newline: string) => Node} Callback */

/**
 * fix callback for *-empty-line-before rules
 * @param {object} o
 * @param {Node} o.node
 * @param {string=} o.newline
 * @param {Callback} o.mutate
 * @param {Range} [o.range]
 * @returns {Range}
 */
function fixEmptyLineBefore({ node, newline, mutate, range }) {
	let count;

	switch (mutate.name) {
		case 'addEmptyLineBefore':
			count = !/\r?\n/.test(node.raws.before) ? -2 : -1;
			break;
		case 'removeEmptyLinesBefore':
			count = (node.raws.before.match(/\n/g) || []).length - 1;
			validateTypes.assert(count > 0);
			break;
		default:
			throw new Error('unknown mutate function');
	}

	validateTypes.assert(newline);
	mutate(node, newline);

	range = range || node.rangeBy({ word: node.toString() });
	range.start.line -= count;
	range.end.line -= count;

	return range;
}

module.exports = fixEmptyLineBefore;
