// NOTICE: This file is generated by Rollup. To modify it,
// please instead edit the ESM counterpart and rebuild with Rollup (npm run build).
'use strict';

/** @import {Config} from 'stylelint' */
/**
 * Parses a configuration object's `overrides` array to create a map of
 * file patterns to their merged configurations.
 *
 * This allows for quick lookups of the complete configuration for a given
 * file pattern.
 *
 * @param {Config} config The raw configuration object.
 * @returns {Object<string, Config>} A map where keys are file patterns and
 * values are the corresponding merged configuration objects.
 */
function generateFileConfigMap(config) {
	if (!config?.overrides || !Array.isArray(config.overrides)) {
		return {};
	}

	/** @type {Map<string, Config>} */
	const fileConfigMap = new Map();

	for (const override of config.overrides) {
		const { files, rules: overrideRules = {}, ...overrideConfig } = override;

		for (const filePattern of files) {
			const currentConfig = fileConfigMap.get(filePattern) || {};

			const newConfig = {
				...currentConfig,
				...overrideConfig,

				rules: {
					...(currentConfig.rules || {}),
					...overrideRules,
				},
			};

			fileConfigMap.set(filePattern, newConfig);
		}
	}

	return Object.fromEntries(fileConfigMap);
}

module.exports = generateFileConfigMap;
