// NOTICE: This file is generated by Rollup. If you want to change,
// please edit its ESM version file instead of this one.
'use strict';

/**
 * @param {import('postcss').AtRule} atRule
 * @returns {string}
 */
function getAtRuleParams(atRule) {
	return atRule.raws.params?.raw ?? atRule.params;
}

module.exports = getAtRuleParams;
