// NOTICE: This file is generated by Rollup. To modify it,
// please instead edit the ESM counterpart and rebuild with Rollup (npm run build).
'use strict';

const constants = require('../constants.cjs');
const dynamicImport = require('./dynamicImport.cjs');
const fs = require('node:fs');
const index = require('../formatters/index.cjs');
const getConfigForFile = require('../getConfigForFile.cjs');
const getFormatterOptionsText = require('./getFormatterOptionsText.cjs');
const path = require('node:path');

/** @import {Formatter, FormatterType, InternalApi} from 'stylelint' */

/**
 * @param {InternalApi} stylelint
 * @param {Object} [params]
 * @param {FormatterType | Formatter | undefined} [params.formatterType]
 * @returns {Promise<Formatter>}
 */
async function getFormatter(stylelint, params = {}) {
	const { formatterType } = params;
	const cwd = stylelint._options.cwd;
	const configPath = stylelint._options.configFile || cwd;
	let formatter = formatterType;

	if (!formatter) {
		let configForFile;

		try {
			configForFile = await getConfigForFile(stylelint, configPath);
		} catch (err) {
			if (err instanceof Error && 'code' in err && err.code === constants.EXIT_CODE_INVALID_CONFIG) {
				configForFile = undefined;
			} else {
				throw err;
			}
		}

		const resolvedConfig = stylelint._options.config ? stylelint._options : configForFile;
		const configFormatter = resolvedConfig?.config.formatter;

		formatter =
			stylelint._options.formatter || configFormatter || stylelint._options._defaultFormatter;
	}

	if (typeof formatter === 'string') {
		const formatterFunction = index[formatter];

		if (formatterFunction === undefined) {
			if (fs.existsSync(formatter)) {
				formatter = await dynamicImport(path.resolve(formatter)).then((m) => m.default);
			} else {
				const formattersText = getFormatterOptionsText(', ', '"');

				throw new Error(`You must use a valid formatter option: ${formattersText} or a function`);
			}
		}

		return formatterFunction;
	}

	if (typeof formatter === 'function') {
		return Promise.resolve(formatter);
	}

	return index.json;
}

module.exports = getFormatter;
