// NOTICE: This file is generated by Rollup. To modify it,
// please instead edit the ESM counterpart and rebuild with Rollup (npm run build).
'use strict';

/**
 * @param {import('stylelint').RuleContext} context
 * @returns {import('css-tree').Lexer}
 */
function getLexer(context) {
	if (!context?.lexer) {
		throw new Error('Expected a "lexer" object');
	}

	return context.lexer;
}

module.exports = getLexer;
