// NOTICE: This file is generated by Rollup. To modify it,
// please instead edit the ESM counterpart and rebuild with Rollup (npm run build).
'use strict';

/**
 * @param {import('stylelint').StylelintPostcssResult} stylelint
 * @returns {import('css-tree').Lexer}
 */
function getLexer(stylelint) {
	if (!stylelint?.lexer) {
		throw new Error('Expected a "lexer" object');
	}

	return stylelint.lexer;
}

module.exports = getLexer;
