// NOTICE: This file is generated by Rollup. To modify it,
// please instead edit the ESM counterpart and rebuild with Rollup (npm run build).
'use strict';

const flattenNestedSelectorsForRule = require('./flattenNestedSelectorsForRule.cjs');
const resolveNestedSelectorsForRule = require('./resolveNestedSelectorsForRule.cjs');

/** @import { Selector, Root } from 'postcss-selector-parser' */
/** @import { Rule } from 'postcss' */
/** @import { PostcssResult } from 'stylelint' */

/**
 * @typedef {{selector: Selector, resolvedSelectors: Root, nested: boolean}} ResolvedSelector
 *
 * @param {Rule} rule
 * @param {PostcssResult} result
 * @returns {Array<ResolvedSelector>}
 */
function getNestedSelectorsForRule(rule, result) {
	if (result.stylelint.config?.languageOptions?.nestingMode === 'native') {
		return resolveNestedSelectorsForRule(rule, result);
	}

	return flattenNestedSelectorsForRule(rule, result);
}

module.exports = getNestedSelectorsForRule;
