// NOTICE: This file is generated by Rollup. To modify it,
// please instead edit the ESM counterpart and rebuild with Rollup (npm run build).
'use strict';

const index = require('../rules/index.cjs');

/**
 * @param {string} ruleName
 * @param {import('stylelint').Config | undefined} [config]
 * @returns {import('stylelint').Rule | undefined}
 */
function getStylelintRule(ruleName, config) {
	return index[ruleName] || (config && config.pluginFunctions && config.pluginFunctions[ruleName]);
}

module.exports = getStylelintRule;
