// NOTICE: This file is generated by Rollup. If you want to change,
// please edit its ESM version file instead of this one.
'use strict';

const HAS_DIMENSION_LIKE_VALUES = /\d[%\w-]/;

/**
 * Check if a value contains any dimension-like values.
 *
 * @param {string} value
 * @returns {boolean}
 */
function hasDimension(value) {
	return HAS_DIMENSION_LIKE_VALUES.test(value);
}

module.exports = hasDimension;
