// NOTICE: This file is generated by Rollup. If you want to change,
// please edit its ESM version file instead of this one.
'use strict';

const HAS_EMPTY_LINE = /\n[\r\t ]*\n/;

/**
 * Check if a string contains at least one empty line
 *
 * @param {string | undefined} string
 * @returns {boolean}
 */
function hasEmptyLine(string) {
	if (string === '' || string === undefined) return false;

	return HAS_EMPTY_LINE.test(string);
}

module.exports = hasEmptyLine;
