// NOTICE: This file is generated by Rollup. If you want to change,
// please edit its ESM version file instead of this one.
'use strict';

const HAS_LESS_INTERPOLATION = /@\{.+?\}/;

/**
 * Check whether a string has less interpolation
 *
 * @param {string} string
 * @return {boolean} If `true`, a string has less interpolation
 */
function hasLessInterpolation(string) {
	return HAS_LESS_INTERPOLATION.test(string);
}

module.exports = hasLessInterpolation;
