// NOTICE: This file is generated by Rollup. If you want to change,
// please edit its ESM version file instead of this one.
'use strict';

const HAS_PSV_INTERPOLATION = /\$\(.+?\)/;

/**
 * Check whether a string has postcss-simple-vars interpolation
 *
 * @param {string} string
 * @returns {boolean}
 */
function hasPsvInterpolation(string) {
	return HAS_PSV_INTERPOLATION.test(string);
}

module.exports = hasPsvInterpolation;
