// NOTICE: This file is generated by Rollup. To modify it,
// please instead edit the ESM counterpart and rebuild with Rollup (npm run build).
'use strict';

const getStylelintRule = require('./getStylelintRule.cjs');

/**
 * @param {import('stylelint').Config} config
 * @returns {Promise<boolean>}
 */
async function hasRulesUsingLexer(config) {
	if (!config.rules) return false;

	const ruleNames = Object.keys(config.rules);

	if (ruleNames.length === 0) return false;

	const loadPromises = ruleNames.map(async (ruleName) => {
		const ruleFn = await getStylelintRule(ruleName, config);

		return ruleFn?.meta?.lexer === 'csstree';
	});

	const boolResults = await Promise.all(loadPromises);

	return boolResults.some((bool) => bool === true);
}

module.exports = hasRulesUsingLexer;
