// NOTICE: This file is generated by Rollup. If you want to change,
// please edit its ESM version file instead of this one.
'use strict';

const HAS_SCSS_INTERPOLATION = /#\{.+?\}/;

/**
 * Check whether a string has scss interpolation
 *
 * @param {string} string
 * @returns {boolean}
 */
function hasScssInterpolation(string) {
	return HAS_SCSS_INTERPOLATION.test(string);
}

module.exports = hasScssInterpolation;
