// NOTICE: This file is generated by Rollup. If you want to change,
// please edit its ESM version file instead of this one.
'use strict';

const HAS_TPL_INTERPOLATION = /\{.+?\}/;

/**
 * Check whether a string has JS template literal interpolation or HTML-like template
 *
 * @param {string} string
 * @return {boolean} If `true`, a string has template literal interpolation
 */
function hasTplInterpolation(string) {
	return HAS_TPL_INTERPOLATION.test(string);
}

module.exports = hasTplInterpolation;
