// NOTICE: This file is generated by Rollup. If you want to change,
// please edit its ESM version file instead of this one.
'use strict';

/**
 * Check whether a media query is a custom
 * @param {string} mediaQuery
 * @returns {boolean}
 */
function isCustomMediaQuery(mediaQuery) {
	return mediaQuery.startsWith('--');
}

module.exports = isCustomMediaQuery;
