// NOTICE: This file is generated by Rollup. If you want to change,
// please edit its ESM version file instead of this one.
'use strict';

/**
 * Check whether a selector is a custom one
 *
 * @param {string} selector
 * @returns {boolean}
 */
function isCustomSelector(selector) {
	return selector.startsWith(':--');
}

module.exports = isCustomSelector;
