// NOTICE: This file is generated by Rollup. To modify it,
// please instead edit the ESM counterpart and rebuild with Rollup (npm run build).
'use strict';

const typeGuards = require('./typeGuards.cjs');
const atKeywords = require('../reference/atKeywords.cjs');

/**
 * Check whether a declaration is a descriptor one
 *
 * @param {import('postcss').Declaration} decl
 * @returns {boolean}
 */
function isDescriptorDeclaration(decl) {
	const { parent } = decl;

	if (parent && typeGuards.isAtRule(parent) && !atKeywords.nestingSupportedAtKeywords.has(parent.name.toLowerCase()))
		return true;

	return false;
}

module.exports = isDescriptorDeclaration;
