// NOTICE: This file is generated by Rollup. If you want to change,
// please edit its ESM version file instead of this one.
'use strict';

const isValidHex = require('./isValidHex.cjs');

/**
 * @param {import('postcss-value-parser').Node} node
 * @returns {boolean}
 */
function isHexColor({ type, value }) {
	return type === 'word' && isValidHex(value);
}

module.exports = isHexColor;
