// NOTICE: This file is generated by Rollup. To modify it,
// please instead edit the ESM counterpart and rebuild with Rollup (npm run build).
'use strict';

const IGNORED_FUNCTIONS = new Set(['url']);

/**
 * @param {import('postcss-value-parser').Node} node
 * @returns {boolean}
 */
function isIgnoredFunction({ type, value }) {
	return type === 'function' && IGNORED_FUNCTIONS.has(value.toLowerCase());
}

module.exports = isIgnoredFunction;
