// NOTICE: This file is generated by Rollup. If you want to change,
// please edit its ESM version file instead of this one.
'use strict';

/**
 * @param {unknown} value
 */
function isNonNegativeInteger(value) {
	return Number.isInteger(value) && typeof value === 'number' && value >= 0;
}

module.exports = isNonNegativeInteger;
