// NOTICE: This file is generated by Rollup. If you want to change,
// please edit its ESM version file instead of this one.
'use strict';

/**
 * Check if a string is a single line (i.e. does not contain
 * any newline characters).
 *
 * @param {string} input
 * @return {boolean}
 */
function isSingleLineString(input) {
	return !/[\n\r]/.test(input);
}

module.exports = isSingleLineString;
