// NOTICE: This file is generated by Rollup. If you want to change,
// please edit its ESM version file instead of this one.
'use strict';

/**
 * Check if a character is whitespace.
 *
 * @param {string} char
 * @returns {boolean}
 */
function isWhitespace(char) {
	return [' ', '\n', '\t', '\r', '\f'].includes(char);
}

module.exports = isWhitespace;
