// NOTICE: This file is generated by Rollup. To modify it,
// please instead edit the ESM counterpart and rebuild with Rollup (npm run build).
'use strict';

const getAtRuleParams = require('./getAtRuleParams.cjs');
const getRuleSelector = require('./getRuleSelector.cjs');
const validateTypes = require('./validateTypes.cjs');

/** @import {AtRule, Declaration, Rule} from 'postcss' */

/**
 * @param {AtRule} atRule
 * @returns {number}
 */
function atRuleParamIndex(atRule) {
	let index = atRuleRawsAfterNameIndex(atRule);

	if (atRule.raws.afterName) {
		index += atRule.raws.afterName.length;
	}

	return index;
}

/**
 * @param {AtRule} node
 * @returns {number}
 */
function atRuleRawsAfterIndex(node) {
	// subtract 1 for `}`

	if (!node.source?.end?.offset) return node.toString().length - 1;

	if (!node.raws?.after?.length) return node.source.end.offset - 1;

	return node.source.end.offset - (node.raws.after.length + 1);
}

/**
 * @param {AtRule} atRule
 * @returns {number}
 */
function atRuleRawsAfterNameIndex(atRule) {
	// Initial 1 is for the `@`
	return 1 + atRule.name.length;
}

/**
 * @param {AtRule} atRule
 * @returns {number}
 */
function atRuleRawsBetweenIndex(atRule) {
	return atRuleParamIndex(atRule) + getAtRuleParams(atRule).length;
}

/**
 * @param {Declaration} decl
 * @returns {number}
 */
function declarationRawsBetweenIndex(decl) {
	const raws = decl.raws;
	const prop = raws.prop;

	return [
		validateTypes.isObject(prop) && 'prefix' in prop && prop.prefix,
		(validateTypes.isObject(prop) && 'raw' in prop && prop.raw) || decl.prop,
		validateTypes.isObject(prop) && 'suffix' in prop && prop.suffix,
	].reduce((/** @type {number} */ count, str) => {
		if (validateTypes.isString(str)) {
			return count + str.length;
		}

		return count;
	}, 0);
}

/**
 * Get the index of a declaration's value
 *
 * @param {Declaration} decl
 * @returns {number}
 */
function declarationValueIndex(decl) {
	const raws = decl.raws;

	return (
		declarationRawsBetweenIndex(decl) +
		[raws.between || ':', raws.value && 'prefix' in raws.value && raws.value.prefix].reduce(
			(/** @type {number} */ count, str) => {
				if (validateTypes.isString(str)) {
					return count + str.length;
				}

				return count;
			},
			0,
		)
	);
}

/**
 * @param {Rule} rule
 * @returns {number}
 */
function ruleRawsBetweenIndex(rule) {
	return getRuleSelector(rule).length;
}

/**
 * @param {Rule} node
 * @returns {number}
 */
function ruleRawsAfterIndex(node) {
	// subtract 1 for `}`

	if (!node.source?.end?.offset) return node.toString().length - 1;

	if (!node.raws?.after?.length) return node.source.end.offset - 1;

	return node.source.end.offset - (node.raws.after.length + 1);
}

exports.atRuleParamIndex = atRuleParamIndex;
exports.atRuleRawsAfterIndex = atRuleRawsAfterIndex;
exports.atRuleRawsAfterNameIndex = atRuleRawsAfterNameIndex;
exports.atRuleRawsBetweenIndex = atRuleRawsBetweenIndex;
exports.declarationRawsBetweenIndex = declarationRawsBetweenIndex;
exports.declarationValueIndex = declarationValueIndex;
exports.ruleRawsAfterIndex = ruleRawsAfterIndex;
exports.ruleRawsBetweenIndex = ruleRawsBetweenIndex;
