// NOTICE: This file is generated by Rollup. To modify it,
// please instead edit the ESM counterpart and rebuild with Rollup (npm run build).
'use strict';

/**
 * Normalize the fix mode based on options and configuration.
 *
 * @param {import('stylelint').LinterOptions} options
 * @param {import('stylelint').Config | undefined} config
 * @returns {'lax' | 'strict' | undefined}
 */
function normalizeFixMode(options, config) {
	let fix = options.fix ?? config?.fix;

	if (fix === true || fix === 'lax') {
		return 'lax';
	}

	if (fix === 'strict') {
		return 'strict';
	}

	return undefined;
}

module.exports = normalizeFixMode;
