// NOTICE: This file is generated by Rollup. To modify it,
// please instead edit the ESM counterpart and rebuild with Rollup (npm run build).
'use strict';

/** @import { Config, FixMode, LinterOptions } from 'stylelint' */

/**
 * Normalize the fix mode based on options and configuration.
 *
 * @param {LinterOptions} options
 * @param {Config | undefined} config
 * @returns {FixMode | undefined}
 */
function normalizeFixMode(options, config) {
	let fix = options.fix ?? config?.fix;

	if (fix === true || fix === 'lax') {
		return 'lax';
	}

	if (fix === 'strict') {
		return 'strict';
	}

	return undefined;
}

module.exports = normalizeFixMode;
