// NOTICE: This file is generated by Rollup. If you want to change,
// please edit its ESM version file instead of this one.
'use strict';

/**
 * Returns the plural form of the given word.
 *
 * @param {string} singular
 * @param {number} count
 * @returns {string}
 */
function pluralize(singular, count) {
	return count === 1 ? singular : `${singular}s`;
}

module.exports = pluralize;
