// NOTICE: This file is generated by Rollup. To modify it,
// please instead edit the ESM counterpart and rebuild with Rollup (npm run build).
'use strict';

const atKeywords = require('../reference/atKeywords.cjs');

const atRulesRegexes = {
	media: /^media$/i,
	keyframes: /^(-(o|moz|ms|webkit)-)?keyframes$/i,
	property: /^property$/i,
	unsupportedNesting: new RegExp(
		`^((?!${[...atKeywords.nestingSupportedAtKeywords.values()].join('|')}).)*$`,
		'i',
	),
};

exports.atRulesRegexes = atRulesRegexes;
