// NOTICE: This file is generated by Rollup. To modify it,
// please instead edit the ESM counterpart and rebuild with Rollup (npm run build).
'use strict';

const atKeywords = require('../reference/atKeywords.cjs');

const atRuleRegexes = {
	mediaName: /^media$/i,
	keyframesName: /^(-(o|moz|ms|webkit)-)?keyframes$/i,
	propertyName: /^property$/i,
	importName: /^import$/i,
	unsupportedNestingNames: new RegExp(
		`^((?!${[...atKeywords.nestingSupportedAtKeywords.values()].join('|')}).)*$`,
		'i',
	),
};

exports.atRuleRegexes = atRuleRegexes;
