// NOTICE: This file is generated by Rollup. To modify it,
// please instead edit the ESM counterpart and rebuild with Rollup (npm run build).
'use strict';

/**
 * @param {import('postcss').Rule} rule
 * @returns {number}
 */
function ruleRawsAfterIndex(rule) {
	return rule.source?.end?.offset ?? rule.toString().length;
}

module.exports = ruleRawsAfterIndex;
