// NOTICE: This file is generated by Rollup. If you want to change,
// please edit its ESM version file instead of this one.
'use strict';

/** @typedef {import('postcss').AtRule} AtRule */

/**
 * @param {AtRule} atRule
 * @param {string} params
 * @returns {AtRule} The atRulearation that was passed in.
 */
function setAtRuleParams(atRule, params) {
	const raws = atRule.raws;

	if (raws.params) {
		raws.params.raw = params;
	} else {
		atRule.params = params;
	}

	return atRule;
}

module.exports = setAtRuleParams;
