// NOTICE: This file is generated by Rollup. To modify it,
// please instead edit the ESM counterpart and rebuild with Rollup (npm run build).
'use strict';

const getRuleSelector = require('../../utils/getRuleSelector.cjs');
const isStandardSyntaxRule = require('../../utils/isStandardSyntaxRule.cjs');
const parseSelector = require('../../utils/parseSelector.cjs');
const report = require('../../utils/report.cjs');
const ruleMessages = require('../../utils/ruleMessages.cjs');
const validateOptions = require('../../utils/validateOptions.cjs');

const ruleName = 'block-no-redundant-nesting';

const messages = ruleMessages(ruleName, {
	rejected: 'Unexpected redundant nesting selector',
});

const meta = {
	url: 'https://stylelint.io/user-guide/rules/block-no-redundant-nesting',
};

/** @type {import('stylelint').CoreRules[ruleName]} */
const rule = (primary) => {
	return (root, result) => {
		const validOptions = validateOptions(result, ruleName, {
			actual: primary,
			possible: [true],
		});

		if (!validOptions) {
			return;
		}

		root.walkRules((ruleNode) => {
			if (!isStandardSyntaxRule(ruleNode)) {
				return;
			}

			const selector = getRuleSelector(ruleNode);

			// Check if this is a redundant nesting selector (just "&")
			if (isRedundantNestingSelector(selector, result, ruleNode)) {
				report({
					message: messages.rejected,
					node: ruleNode,
					result,
					ruleName,
				});
			}
		});
	};
};

/**
 * Check if a selector is a redundant nesting selector
 * @param {string} selector
 * @param {import('stylelint').PostcssResult} result
 * @param {import('postcss').Rule} ruleNode
 * @returns {boolean}
 */
function isRedundantNestingSelector(selector, result, ruleNode) {
	const selectorRoot = parseSelector(selector, result, ruleNode);

	if (!selectorRoot) return false;

	return selectorRoot.every((selectorNode) => {
		// A redundant nesting selector is one that contains only a nesting selector (&)
		// with no additional qualifiers, descendants, or pseudo-elements
		const { nodes } = selectorNode;

		// Should have exactly one node which is a nesting selector
		if (nodes.length !== 1) return false;

		const firstNode = nodes[0];

		// Check if it's a nesting selector (&)
		return Boolean(firstNode && firstNode.type === 'nesting' && firstNode.value === '&');
	});
}

rule.ruleName = ruleName;
rule.messages = messages;
rule.meta = meta;

module.exports = rule;
