export {
	default,
	Config,
	ConfigRuleSettings,
	CoreRules,
	CosmiconfigResult,
	CssSyntaxError,
	CustomSyntax,
	DisableOptions,
	DisableOptionsReport,
	DisablePropertyName,
	DisableReportRange,
	DisabledRange,
	DisabledRangeObject,
	DisabledWarning,
	FixCallback,
	FixMode,
	FixObject,
	Formatter,
	FormatterType,
	GetLintSourceOptions,
	GetPostcssOptions,
	InternalApi,
	LintResult,
	LinterOptions,
	LinterResult,
	LonghandSubPropertiesOfShorthandProperties,
	Plugin,
	PostcssPluginOptions,
	PostcssResult,
	Problem,
	Processor,
	PublicApi,
	Range,
	Rule,
	RuleBase,
	RuleContext,
	RuleMessage,
	RuleMessages,
	RuleMeta,
	RuleOptions,
	RuleOptionsPossible,
	Severity,
	ShorthandProperties,
	StylelintPostcssResult,
	SuppressedProblems,
	Utils,
	Warning,
	WarningOptions,
} from './index.js';

import type {Config} from './index.js';

/**
 * Define a Stylelint configuration.
 */
export function defineConfig<T = Config>(config: T): T;
