// NOTICE: This file is generated by Rollup. To modify it,
// please instead edit the ESM counterpart and rebuild with Rollup (npm run build).
'use strict';

const validateTypes = require('../../utils/validateTypes.cjs');
const properties = require('../../reference/properties.cjs');
const isCustomProperty = require('../../utils/isCustomProperty.cjs');
const isStandardSyntaxProperty = require('../../utils/isStandardSyntaxProperty.cjs');
const matchesStringOrRegExp = require('../../utils/matchesStringOrRegExp.cjs');
const report = require('../../utils/report.cjs');
const ruleMessages = require('../../utils/ruleMessages.cjs');
const validateOptions = require('../../utils/validateOptions.cjs');
const vendor = require('../../utils/vendor.cjs');

const ruleName = 'property-layout-mappings';

const messages = ruleMessages(ruleName, {
	expected: (actual, expected) => `Expected "${actual}" to be "${expected}"`,
});

const meta = {
	url: 'https://stylelint.io/user-guide/rules/property-layout-mappings',
	fixable: true,
};

/** @type {import('stylelint').CoreRules[ruleName]} */
const rule = (primary, secondaryOptions) => {
	return (root, result) => {
		const validOptions = validateOptions(
			result,
			ruleName,
			{
				actual: primary,
				possible: ['logical', 'physical'],
			},
			{
				actual: secondaryOptions,
				possible: {
					exceptProperties: [validateTypes.isString, validateTypes.isRegExp],
				},
				optional: true,
			},
		);

		if (!validOptions) {
			return;
		}

		const exceptProperties = secondaryOptions?.exceptProperties ?? [];
		const isLogicalMode = primary === 'logical';

		root.walkDecls((decl) => {
			const prop = decl.prop;

			if (!isStandardSyntaxProperty(prop)) return;

			if (isCustomProperty(prop)) return;

			const unprefixedProp = vendor.unprefixed(prop);

			// Skip if property is in except list
			if (matchesStringOrRegExp([prop, unprefixedProp], exceptProperties)) return;

			let expectedProp;
			let mappingFound = false;

			if (isLogicalMode) {
				// In logical mode, flag physical properties
				if (properties.physicalToLogicalProperties.has(unprefixedProp)) {
					expectedProp = properties.physicalToLogicalProperties.get(unprefixedProp);
					mappingFound = true;
				}
			} else if (properties.logicalToPhysicalProperties.has(unprefixedProp)) {
				// In physical mode, flag logical properties
				expectedProp = properties.logicalToPhysicalProperties.get(unprefixedProp);
				mappingFound = true;
			}

			if (!mappingFound) return;

			// Preserve vendor prefix if present
			const prefix = vendor.prefix(prop);
			const expectedPropWithPrefix = prefix + expectedProp;

			report({
				message: messages.expected,
				messageArgs: [prop, expectedPropWithPrefix],
				word: prop,
				node: decl,
				result,
				ruleName,
				fix() {
					decl.prop = expectedPropWithPrefix;
				},
			});
		});
	};
};

rule.primaryOptionArray = false;
rule.ruleName = ruleName;
rule.messages = messages;
rule.meta = meta;

module.exports = rule;
