name: Preparing GitHub Release

on:
  push:
    tags:
      - '**'

permissions:
  contents: write

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: npm

      - name: Install latest npm
        run: npm install --global npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Extract changelog entries
        run: npm run changelog-to-github-release --silent > /tmp/changes.md

      - name: Create draft release
        run: gh release create "${GITHUB_REF_NAME}" --draft --notes-file /tmp/changes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
