name: Preparing GitHub Release

on:
  push:
    tags:
      - '**'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare release
        uses: stylelint/changelog-to-github-release-action@944dfc1b76b778a9d57df65c88e5be7558e05d90 # 0.3.0
        with:
          tag: ${{ github.ref_name }}
          draft: true
