name: Preparing GitHub Release

on:
  push:
    tags:
      - '**'

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare release
        uses: ybiquitous/changelog-to-github-release-action@main
        with:
          tag: ${{ github.ref_name }}
          draft: true
