name: Release PR

on:
  workflow_dispatch:

jobs:
  release-pr:
    uses: stylelint/.github/.github/workflows/call-release-pr.yml@de22fededfbe64a953912f8306e71923d7a503d3 # 1.0.1
    with:
      new-version-command: 'npm run changeset && npm install --ignore-scripts'
    permissions:
      contents: write
      pull-requests: write
