name: Release

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  release:
    uses: stylelint/.github/.github/workflows/call-release.yml@38848ee8badc3888f246692cc371d519616d74e2 # 0.9.0
    permissions:
      contents: write
      id-token: write
