name: Release PR

on:
  workflow_dispatch:

jobs:
  release-pr:
    uses: stylelint/.github/.github/workflows/call-release-pr.yml@ab7979355590956aa96d306dedfda6b2d42c4982 # 1.1.0
    with:
      new-version-command: 'npm run changeset && npm install --ignore-scripts'
    permissions:
      contents: write
      pull-requests: write
