name: Release PR

on:
  workflow_dispatch:

jobs:
  release-pr:
    uses: stylelint/.github/.github/workflows/call-release-pr.yml@6ac761787832e417273f7bb071ec8cf35abcc3d6 # 1.0.0
    with:
      new-version-command: 'npm run changeset && npm install --ignore-scripts'
    permissions:
      contents: write
      pull-requests: write
