name: Release

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  release:
    uses: stylelint/.github/.github/workflows/call-release.yml@56c5d6e7e35009b7748db7558eac5377ec88f446 # 0.6.1
    permissions:
      contents: write
      id-token: write
