name: Release

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  release:
    uses: stylelint/.github/.github/workflows/call-release.yml@ab7979355590956aa96d306dedfda6b2d42c4982 # 1.1.0
    permissions:
      contents: write
      id-token: write
