// NOTICE: This file is generated by Rollup. To modify it,
// please instead edit the ESM counterpart and rebuild with Rollup (npm run build).
'use strict';

/**
 * @see https://drafts.csswg.org/mediaqueries/#ref-for-media-type①⑨
 * @type {ReadonlySet<string>}
 */
const deprecatedMediaTypesNames = new Set([
	'tty',
	'tv',
	'projection',
	'handheld',
	'braille',
	'embossed',
	'aural',
	'speech',
]);

exports.deprecatedMediaTypesNames = deprecatedMediaTypesNames;
