// NOTICE: This file is generated by Rollup. If you want to change,
// please edit its ESM version file instead of this one.
'use strict';

const prefixes = new Set(['-webkit-', '-moz-', '-ms-', '-o-']);

exports.prefixes = prefixes;
