"use strict"

module.exports = {
  "margin": [
    "margin-top",
    "margin-bottom",
    "margin-left",
    "margin-right",
  ],
  "padding": [
    "padding-top",
    "padding-bottom",
    "padding-left",
    "padding-right",
  ],
  "background": [
    "background-image",
    "background-size",
    "background-position",
    "background-repeat",
    "background-origin",
    "background-clip",
    "background-attachment",
    "background-color",
  ],
  "font": [
    "font-style",
    "font-variant",
    "font-weight",
    "font-stretch",
    "font-size",
    "font-family",
    "line-height",
  ],
  "border": [
    "border-top-width",
    "border-bottom-width",
    "border-left-width",
    "border-right-width",
    "border-top-style",
    "border-bottom-style",
    "border-left-style",
    "border-right-style",
    "border-top-color",
    "border-bottom-color",
    "border-left-color",
    "border-right-color",
  ],
  "border-top": [
    "border-top-width",
    "border-top-style",
    "border-top-color",
  ],
  "border-bottom": [
    "border-bottom-width",
    "border-bottom-style",
    "border-bottom-color",
  ],
  "border-left": [
    "border-left-width",
    "border-left-style",
    "border-left-color",
  ],
  "border-right": [
    "border-right-width",
    "border-right-style",
    "border-right-color",
  ],
  "border-width": [
    "border-top-width",
    "border-bottom-width",
    "border-left-width",
    "border-right-width",
  ],
  "border-style": [
    "border-top-style",
    "border-bottom-style",
    "border-left-style",
    "border-right-style",
  ],
  "border-color": [
    "border-top-color",
    "border-bottom-color",
    "border-left-color",
    "border-right-color",
  ],
  "list-style": [
    "list-style-type",
    "list-style-position",
    "list-style-image",
  ],
  "border-radius": [
    "border-top-right-radius",
    "border-top-left-radius",
    "border-bottom-right-radius",
    "border-bottom-left-radius",
  ],
  "transition": [
    "transition-delay",
    "transition-duration",
    "transition-property",
    "transition-timing-function",
  ],
  "-webkit-transition": [
    "-webkit-transition-delay",
    "-webkit-transition-duration",
    "-webkit-transition-property",
    "-webkit-transition-timing-function",
  ],
  "-moz-transition": [
    "-moz-transition-delay",
    "-moz-transition-duration",
    "-moz-transition-property",
    "-moz-transition-timing-function",
  ],
  "-o-transition": [ "-o-transition-delay",
    "-o-transition-duration",
    "-o-transition-property",
    "-o-transition-timing-function" ],
}
