'use strict';

module.exports = {
	margin: new Set(['margin-top', 'margin-bottom', 'margin-left', 'margin-right']),
	padding: new Set(['padding-top', 'padding-bottom', 'padding-left', 'padding-right']),
	background: new Set([
		'background-image',
		'background-size',
		'background-position',
		'background-repeat',
		'background-origin',
		'background-clip',
		'background-attachment',
		'background-color',
	]),
	font: new Set([
		'font-style',
		'font-variant',
		'font-weight',
		'font-stretch',
		'font-size',
		'font-family',
		'line-height',
	]),
	border: new Set([
		'border-top-width',
		'border-bottom-width',
		'border-left-width',
		'border-right-width',
		'border-top-style',
		'border-bottom-style',
		'border-left-style',
		'border-right-style',
		'border-top-color',
		'border-bottom-color',
		'border-left-color',
		'border-right-color',
	]),
	'border-top': new Set(['border-top-width', 'border-top-style', 'border-top-color']),
	'border-bottom': new Set(['border-bottom-width', 'border-bottom-style', 'border-bottom-color']),
	'border-left': new Set(['border-left-width', 'border-left-style', 'border-left-color']),
	'border-right': new Set(['border-right-width', 'border-right-style', 'border-right-color']),
	'border-width': new Set([
		'border-top-width',
		'border-bottom-width',
		'border-left-width',
		'border-right-width',
	]),
	'border-style': new Set([
		'border-top-style',
		'border-bottom-style',
		'border-left-style',
		'border-right-style',
	]),
	'border-color': new Set([
		'border-top-color',
		'border-bottom-color',
		'border-left-color',
		'border-right-color',
	]),
	'list-style': new Set(['list-style-type', 'list-style-position', 'list-style-image']),
	'border-radius': new Set([
		'border-top-right-radius',
		'border-top-left-radius',
		'border-bottom-right-radius',
		'border-bottom-left-radius',
	]),
	transition: new Set([
		'transition-delay',
		'transition-duration',
		'transition-property',
		'transition-timing-function',
	]),
	animation: new Set([
		'animation-name',
		'animation-duration',
		'animation-timing-function',
		'animation-delay',
		'animation-iteration-count',
		'animation-direction',
		'animation-fill-mode',
		'animation-play-state',
	]),
	'border-block-end': new Set([
		'border-block-end-width',
		'border-block-end-style',
		'border-block-end-color',
	]),
	'border-block-start': new Set([
		'border-block-start-width',
		'border-block-start-style',
		'border-block-start-color',
	]),
	'border-image': new Set([
		'border-image-source',
		'border-image-slice',
		'border-image-width',
		'border-image-outset',
		'border-image-repeat',
	]),
	'border-inline-end': new Set([
		'border-inline-end-width',
		'border-inline-end-style',
		'border-inline-end-color',
	]),
	'border-inline-start': new Set([
		'border-inline-start-width',
		'border-inline-start-style',
		'border-inline-start-color',
	]),
	'column-rule': new Set(['column-rule-width', 'column-rule-style', 'column-rule-color']),
	columns: new Set(['column-width', 'column-count']),
	flex: new Set(['flex-grow', 'flex-shrink', 'flex-basis']),
	'flex-flow': new Set(['flex-direction', 'flex-wrap']),
	grid: new Set([
		'grid-template-rows',
		'grid-template-columns',
		'grid-template-areas',
		'grid-auto-rows',
		'grid-auto-columns',
		'grid-auto-flow',
		'grid-column-gap',
		'grid-row-gap',
	]),
	'grid-area': new Set(['grid-row-start', 'grid-column-start', 'grid-row-end', 'grid-column-end']),
	'grid-column': new Set(['grid-column-start', 'grid-column-end']),
	'grid-gap': new Set(['grid-row-gap', 'grid-column-gap']),
	'grid-row': new Set(['grid-row-start', 'grid-row-end']),
	'grid-template': new Set(['grid-template-columns', 'grid-template-rows', 'grid-template-areas']),
	outline: new Set(['outline-color', 'outline-style', 'outline-width']),
	'text-decoration': new Set([
		'text-decoration-color',
		'text-decoration-style',
		'text-decoration-line',
	]),
	'text-emphasis': new Set(['text-emphasis-style', 'text-emphasis-color']),
	mask: new Set([
		'mask-image',
		'mask-mode',
		'mask-position',
		'mask-size',
		'mask-repeat',
		'mask-origin',
		'mask-clip',
		'mask-composite',
	]),
};
